version: '2'
services:

  backend:
    build: ./backend
    ports:
      - "9001:9001"
    links:
      - redis
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "9000:9000"

  redis:
    image: redis:latest

  mongo:
    image: mongo:latest